name: Code coverage
run-name: ${{ github.actor }} is executing code coverage Actions
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running the code coverage"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: go mod download
      - name: Run tests and generate coverage report
        run: go test -race -coverprofile=coverage.xml ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          #token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          version: "v0.1.15"
