name: Code coverage
run-name: ${{ github.actor }} is executing code coverage Actions
on:
  pull_request:
    branches:
      - main

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running the code coverage"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: go mod download
      - name: Run tests and generate coverage report
        run: go test -coverprofile=coverage.out -covermode=count ./...
      - name: Comment code coverage on PR
        run: |
          set -x
          totalcc=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "total_cc=$totalcc" >> $GITHUB_ENV
      - name: Comment on Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Code coverage of feature folder is ${{env.total_cc}}% Please add more test cases!'
            })
               